### ISSUE TITLE
Freedesktop SDK 24.08 will be dropping appstream-compose

### ISSUE THREAD

**Issue by bbhtt** [flathub/org.kicad.KiCad.ODBCDriver.mariadb-connector-odbc#18]
Please remove manual compose or switch to appstreamcli 

See https://docs.flatpak.org/en/latest/extension.html#extension-manifest for the commands

**Comment by jmaibaum** [comment]
Thanks for the heads up. I will look into it (for all related KiCad extensions) when I find time.
